FROM rust:1.75 as builder

WORKDIR /app

COPY Cargo.toml ./
COPY src ./src

RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/goflow2-aggregator /app/goflow2-aggregator

EXPOSE 9090

ENV RUST_LOG=info

CMD ["/app/goflow2-aggregator"]
